services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: curral
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - curral_pgdata:/var/lib/postgresql/data

volumes:
  curral_pgdata:
